### PR TITLE
Fix DeleteRequest and extend xhr

### PR DESCRIPTION
**Pull request by timbar365**

### CODE REVIEW

**Comment by timbar365** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders

**Comment by timbar365** [comment]
Hi @jordimontana82, any chances to get this into your repo? Thanks

**Comment by jordimontana82** [comment]
This has been merged now, sorry for the delay... and happy new year by the way! :)

**Comment by jordimontana82** [comment]
This has been pushed to 1.0.9 now.

**Pull request merged**
